### ISSUE TITLE
Deploye your webiste with either Heroku , netlifycms , or firebase

### ISSUE THREAD

**Issue by madilraza** [froheel/EcoChange#1]
I looked at you web site it looks great i want to help you and work on the deployment of your website. 
either on Heroku netlify  firebase or even you can host your website with custom domain on github pages i will love to work on it

**Comment by froheel** [comment]
Hi @madilraza,
Firstly, thank you for the kind compliment. Wow, I would love to collaborate with you and get this project in a running state and host it. Let's continue this discussion on email. You can comment your email and I will contact you . I look forward to hear from you soon.

**Comment by madilraza** [comment]
ary18sw18@gmail.com
https://www.facebook.com/adilyounad.malik
https://www.linkedin.com/in/muhammad-adil-419544183/ 
you can contact on any of the media you take eas lets to begin it with fully-functional working site

**Comment by froheel** [comment]
I apologize for reaching out so late. Kindly check your inbox, I have sent you an email. Looking forward to your reply.
